
#In the lab where I'm currently working at, the internet is configured to block me from accessing a
#remote postgres 16 db on render which is used by my spring app to operate.

#just because of that i'm using docker locally to run a dev database

# in the command line:
# docker-compose -f docker-compose-only-dev.yml up -d

services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: R4f4MR3HqoqhperVwOUvMDqP0vzsmdd4
      POSTGRES_DB: lacmdb
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'      # Limita a 0.5 CPU cores (~3% de Ryzen 9 7940HS)
          memory: 1G       # Limita a 1GB de RAM
        reservations:
          cpus: '0.1'      # Reserva mínima de 0.1 CPU cores
          memory: 256M     # Reserva mínima de 256MB de RAM
